apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-repo-cybera
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
  - repoURL: 'https://github.com/chrisf-aarnet/mock-detections.git'
    path: charts/eng-helm   # NB: set the path to the top of the chart directory, ArgoCD will autodetect and run helm
    targetRevision: HEAD
    helm:
      valueFiles:
      - $values/customers/cybera/values.yaml   # NB: this is a single Application, not an ApplicationSet so it references only one customer values.yaml file
  - repoURL: 'https://github.com/chrisf-aarnet/mock-customers.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
