apiVersion: v1
kind: ConfigMap
metadata:
  name: debug-plugin
  namespace: argocd
data:
  pluginName.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: debug-plugin
    spec:
      init:                          # Optional command to initialize application source directory
        command: ["pwd"]
        args: [""]
      generate:                      # Command to generate Kubernetes Objects in either YAML or JSON
        command: ["ls -lRa"]
        args: [""]