---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cisco-nso-config
  labels:
    app.aarnet.edu.au: cisco-nso
    stack.aarnet.edu.au: {{ .Values.stack }}
data:
  index.html: |
    I'm {{ .Values.stack }}-{{ .Values.cust_code }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cisco-nso-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.aarnet.edu.au: cisco-nso
  template:
    metadata:
      labels:
        app.aarnet.edu.au: cisco-nso
        stack.aarnet.edu.au: {{ .Values.stack }}
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
          - name: static-content
            mountPath: /usr/share/nginx/html
            readOnly: true
      volumes:
      - name: static-content
        configMap:
          name: cisco-nso-config

---
apiVersion: v1
kind: Service
metadata:
  name: cisco-nso
  labels:
    stack.aarnet.edu.au: {{ .Values.stack }}
spec:
  selector:
    app.aarnet.edu.au: cisco-nso
  ports:
    - port: 80
      targetPort: 80
