---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config-{{ .Values.stack }}-{{ .Values.cust_code }}
  labels:
    cust_code.aarnet.edu.au: {{ .Values.cust_code }}
    stack.aarnet.edu.au: {{ .Values.stack }}
data:
  index.html: |
    I'm {{ .Values.stack }}-{{ .Values.cust_code }}
